name: flutter_boilerplate
description: A simple boilerplate project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  auto_route: 5.0.1
  intl: ^0.17.0
  meta: ^1.8.0
  dio: ^4.0.6
  json_annotation: ^4.7.0
  pretty_dio_logger: ^1.1.1
  flutter_secure_storage: 6.0.0
  google_fonts: ^3.0.1
  lottie: ^1.4.3
  connectivity_plus: ^2.3.9
  shared_preferences: ^2.0.15
  flutter_dotenv: ^5.0.2


dev_dependencies:
  #flutter_test:
    #sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  dart_code_metrics: 4.19.1
  very_good_performance: ^0.0.4
  dependency_validator: ^3.2.2
  json_serializable:
  build_runner:
  flutter_gen_runner:
  freezed: ^2.1.0+1
  auto_route_generator: 5.0.2
  logger:
  import_sorter: ^4.6.0

## Install derry from https://pub.dev/packages/derry and run derry build, derry watch, derry gen
scripts: derry.yaml

# https://pub.dev/packages/flutter_gen, after new assets run derry gen
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)

  #  integrations:
  #    flutter_svg: true
  #    flare_flutter: true

  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/*
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/env/.env.production
    - assets/env/.env.staging
    - assets/env/.env.development
    - assets/env/
    - assets/
    #- assets/image/
